Initialize member variables by constructor in moveit_ros
robo-marc/moveit pull request #34
Opened 2019-12-11 07:40 UTC by KazukiHazama

### Description

In `octomap_render.cpp`, member variable `scene_manager_` is uninitialized and used without checking.
This fix adds an initializer its in constructor.
These values based on existing them in same source(default or non-influence value).

2020-01-23 07:47 UTC, r-kurose requested changes

2020-01-23 07:47 UTC, r-kurose commented on moveit_ros/visualization/rviz_plugin_render_tools/src/octomap_render.cpp
> +  scene_manager_ = scene_manager;
This line is redundant.

2020-01-27 06:10 UTC, KazukiHazama commented on moveit_ros/visualization/rviz_plugin_render_tools/src/octomap_render.cpp
> +  scene_manager_ = scene_manager;
Fix in commit 1236203.

2020-01-31 02:14 UTC, r-kurose commented on moveit_ros/visualization/rviz_plugin_render_tools/src/octomap_render.cpp
> +  scene_manager_ = scene_manager;
OK

2020-01-31 02:14 UTC, merged